# Add your Google Earth Engine service account key here
# Get it from: https://console.cloud.google.com/iam-admin/serviceaccounts
# Create new key -> JSON -> paste the entire JSON content below as a string

[gee]
service_account = '''
{
  "type": "service_account",
  "project_id": "your-project-id",
  "private_key_id": "...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token"
}
'''